# Generated by Django 4.2.6 on 2023-10-21 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Periodicity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='периодичность')),
            ],
            options={
                'verbose_name': 'периодичность',
                'verbose_name_plural': 'периодичность',
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='название рассылки')),
                ('title', models.CharField(max_length=100, verbose_name='тема письма')),
                ('body', models.TextField(verbose_name='тело письма')),
                ('start_time', models.TimeField(default='00:00:00', verbose_name='время начала')),
                ('stop_time', models.TimeField(default='00:10:00', verbose_name='длительность')),
                ('status', models.CharField(default='создана', max_length=10, verbose_name='статус')),
                ('is_active', models.BooleanField(default=True, verbose_name='включить')),
                ('periodicity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_app.periodicity', verbose_name='периодичность')),
            ],
            options={
                'verbose_name': 'рассылку',
                'verbose_name_plural': 'рассылки',
            },
        ),
    ]
