# Generated by Django 4.2.6 on 2023-10-22 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='тема письма')),
                ('body', models.TextField(verbose_name='тело письма')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='название рассылки')),
                ('periodic', models.CharField(choices=[('MIN', 'Минута'), ('H', 'Час'), ('D', 'День'), ('W', 'Неделя'), ('M', 'Месяц'), ('Y', 'Год')], default='D', max_length=3, verbose_name='периодичность')),
                ('start_time', models.DateTimeField(verbose_name='начало рассылки')),
                ('stop_time', models.DateTimeField(verbose_name='окончание рассылки')),
                ('sending_time', models.DateTimeField(blank=True, null=True, verbose_name='время успешной отправки')),
                ('status', models.CharField(choices=[('CR', 'Создана'), ('LA', 'Запущена'), ('CP', 'Завершена')], default='CR', max_length=2, verbose_name='статус')),
                ('is_active', models.BooleanField(default=True, verbose_name='активна')),
                ('customers', models.ManyToManyField(to='customers_app.customer', verbose_name='клиенты')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service_app.message', verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'рассылку',
                'verbose_name_plural': 'рассылки',
            },
        ),
    ]
