# Generated by Django 4.2.6 on 2023-10-22 01:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='начало рассылки'),
        ),
    ]
