# Generated by Django 4.2.6 on 2023-10-21 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodicity',
            name='time',
            field=models.IntegerField(default=7, verbose_name='периодичность дней'),
        ),
    ]
