# Generated by Django 4.2.6 on 2023-10-21 07:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0002_periodicity_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='periodicity',
            name='time',
        ),
        migrations.AddField(
            model_name='periodicity',
            name='days',
            field=models.IntegerField(default=7, validators=[django.core.validators.MaxValueValidator(360)], verbose_name='дни'),
        ),
        migrations.AddField(
            model_name='periodicity',
            name='hours',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(24)], verbose_name='часы'),
        ),
        migrations.AddField(
            model_name='periodicity',
            name='minutes',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(60)], verbose_name='минуты'),
        ),
    ]
