# Generated by Django 4.2.6 on 2023-10-21 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0003_remove_periodicity_time_periodicity_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='sending_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='время успешной отправки'),
        ),
    ]
