# Generated by Django 4.2.6 on 2023-10-22 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0003_alter_mailing_stop_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailing',
            name='sending_time',
        ),
    ]
