# Generated by Django 4.2.6 on 2023-10-22 04:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0004_remove_mailing_sending_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='send_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='последняя отправка'),
        ),
    ]
