# Generated by Django 4.2.6 on 2023-10-22 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0008_alter_mailing_periodic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='periodic',
            field=models.CharField(choices=[('0:01:00', 'Минута'), ('1:00:00', 'Час'), ('1 day, 0:00:00', 'День'), ('7 days, 0:00:00', 'Неделя'), ('30 days, 0:00:00', 'Месяц'), ('365 days, 0:00:00', 'Год')], default='1 day, 0:00:00', max_length=30, verbose_name='периодичность'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='send_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='последняя отправка'),
        ),
    ]
