# Generated by Django 4.2.6 on 2023-10-22 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0009_alter_mailing_periodic_alter_mailing_send_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='periodic',
            field=models.IntegerField(choices=[(1, 'Минута'), (60, 'Час'), (720, 'День'), (5040, 'Неделя'), (21600, 'Месяц'), (262800, 'Год')], default=720, verbose_name='периодичность'),
        ),
    ]
