# Generated by Django 4.2.6 on 2023-10-22 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0010_alter_mailing_periodic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailing',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='mailing',
            name='periodic',
            field=models.IntegerField(choices=[(1, 'Минута'), (60, 'Час'), (1440, 'День'), (10080, 'Неделя'), (43200, 'Месяц'), (525600, 'Год')], default=1440, verbose_name='периодичность'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='status',
            field=models.CharField(choices=[('CR', 'Создана'), ('LA', 'Запущена'), ('CP', 'Завершена'), ('PA', 'Приостановлена')], default='CR', max_length=2, verbose_name='статус'),
        ),
    ]
