# Generated by Django 4.2.6 on 2023-10-22 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0011_remove_mailing_is_active_alter_mailing_periodic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='status',
            field=models.CharField(choices=[('CR', 'Создана'), ('LA', 'Запущена'), ('CP', 'Завершена'), ('PA', 'Пауза')], default='CR', max_length=2, verbose_name='статус'),
        ),
    ]
