# Generated by Django 4.2.6 on 2023-10-18 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service_app', '0001_initial'),
        ('customers_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_attempt', models.DateTimeField(verbose_name='дата и время последней попытки')),
                ('attempt_status', models.CharField(max_length=20, verbose_name='статус попытки')),
                ('server_response', models.IntegerField(blank=True, null=True, verbose_name='ответ почтового сервера, если он был')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers_app.customer', verbose_name='Клиент')),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_app.mailing', verbose_name='рассылка')),
            ],
            options={
                'verbose_name': 'попытку',
                'verbose_name_plural': 'попытки',
            },
        ),
    ]
