# Generated by Django 4.2.6 on 2023-10-22 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_attempt', models.DateTimeField(auto_now_add=True, verbose_name='дата и время последней попытки')),
                ('server_response', models.CharField(blank=True, max_length=250, null=True, verbose_name='ответ почтового сервера, если он был')),
                ('is_successfully', models.BooleanField(default=False, verbose_name='статус попытки')),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_app.mailing', verbose_name='рассылка')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Рассылки',
            },
        ),
    ]
