# Generated by Django 4.2.6 on 2023-10-21 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailinglog',
            name='is_successfully',
            field=models.BooleanField(default=False, verbose_name='успешно'),
        ),
    ]
