# Generated by Django 4.2.6 on 2023-10-22 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailinglog',
            name='mode',
            field=models.CharField(blank=True, choices=[('A', 'Автоматический'), ('M', 'Ручной')], max_length=1, null=True, verbose_name='режим отправки'),
        ),
    ]
