# Generated by Django 4.2.6 on 2023-10-21 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logger_app', '0002_mailinglog_is_successfully'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailinglog',
            name='is_successfully',
        ),
    ]
