# Generated by Django 4.2.6 on 2023-10-21 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger_app', '0003_remove_mailinglog_is_successfully'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailinglog',
            name='attempt_status',
        ),
        migrations.AddField(
            model_name='mailinglog',
            name='is_successfully',
            field=models.BooleanField(default=False, verbose_name='статус попытки'),
        ),
    ]
