# Generated by Django 4.2.6 on 2023-10-22 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='is_mailing',
            field=models.BooleanField(default=True, verbose_name='подписка на рассылки'),
        ),
    ]
